name: "Hello World Action"
description: "Greet someone"
inputs:
  who-to-greet:
    description: "The name of the person to greet"
    required: true
    default: "World"

outputs:
  time:
    description: "The time the greeting happened"
    
runs:
  using: node20
  main: dist/index.js